program: trainOffline.py
method: bayes
name : Knot_offline
metric:
  goal: maximize
  name: success_rate
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  num_layers:
    values: [1,2,3]
  hidden_layer_size:
    value: 128
  actor_lr:
    min: 0.000001
    max: 0.01
  critic_lr:
    min: 0.000001
    max: 0.01
  gamma:
    values: [0.9,0.95,0.99]
  min_q_weight:
    min: 0.001
    max: 0.5
  explore:
    min: 0
    max: 2
  tau:
    value: 0.000005
  max_epochs:
    value: 100
  batch_size: 
    value: 32
  steps_per_epoch:
    value: 2000
  goal_threshold:
    value: 0.4
  dataset_path: 
    value: "Datasets/Prior/Data.pkl"
