program: trainStraightenOffline.py
method: bayes
name : Straighten_test
metric:
  goal: maximize
  name: val_return
parameters:
  num_layers:
    values: [1,2,3]
  hidden_layer_size:
    value: 128
  actor_lr:
    min: 0.00001
    max: 0.1
  critic_lr:
    min: 0.00001
    max: 0.1
  gamma:
    values: [0.9,0.95,0.99]
  min_q_weight:
    min: 0.001
    max: 0.5
  explore:
    min: 0
    max: 2
  tau:
    value: 0.000005
  max_epochs:
    value: 200
  batch_size: 
    values: [16,32,64]
  steps_per_epoch:
    value: 500
  dataset_path: 
    value: "Datasets/Random/Data.pkl"
