program: trainOffline2.py
method: bayes
name : offlineRL_sweep
metric:
  goal: minimize
  name: actor_loss
parameters:
  num_layers:
    values: [1,2,3]
  hidden_layer_size:
    value: 128
  actor_lr:
    min: 0.0001
    max: 0.1
  critic_lr:
    min: 0.0001
    max: 0.1
  gamma:
    values: [0.9,0.95,0.99]
  min_q_weight:
    min: 0.01
    max: 0.5
  explore:
    min: 0
    max: 2
  tau:
    value: 0.000005
  max_epochs:
    value: 200
  batch_size: 
    values: [16,32,64]
  steps_per_epoch:
    values: [1000,2000,4000]
  dataset_path: 
    value: "Datasets/dataset2.pkl"
