program: trainOffline.py
method: bayes
name : offlineRL_sweep
metric:
  goal: minimize
  name: actor_validation_loss
parameters:
  max_epochs:
    value: 200
  tau:
    value: 0.000005
  batch_size: 
    values: [16,32,64]
  actor_lr:
    min : 0.0001
    max : 0.1
  critic_lr:
    min : 0.0001
    max : 0.1
  gamma:
    values: [0.9,0.95,0.99]
  dataset_path: 
    value: "Datasets/dataset2.pkl"
